version: "3.9"

services:
  reflector:
    build:
      context: .
      dockerfile: reflector/Dockerfile
  server1:
    build:
      context: .
      dockerfile: spongecoin/Dockerfile
  server2:
    build:
      context: .
      dockerfile: spongecoin/Dockerfile2
  client1:
    build:
      context: .
      dockerfile: ui/Dockerfile
  client2:
    build:
      context: .
      dockerfile: ui/Dockerfile
  nginx:
    image: nginx:1.22-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
