version: "3.9"

services:
  spongechain:
    command: [ "echo", "built image" ]
    build:
      context: .
      dockerfile: spongechain/Dockerfile
    volumes:
      - blockchain:/data/spongechain
    networks:
      - frontend
  ui:
    command: [ "echo", "built image" ]
    build:
      context: .
      dockerfile: ui/Dockerfile
    networks:
      - frontend
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/access.log:/etc/nginx/access.log
      - ./nginx/error.log:/etc/nginx/error.log
    ports:
      - "80:80"
    networks:
      - frontend
networks:
  frontend: null
volumes:
  blockchain: null
