version: "3.9"

services:
  spongecoin:
    build:
      context: .
      dockerfile: spongecoin/Dockerfile
  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
  nginx:
    image: nginx:1.22-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
